services:
  - type: web
    name: api
    env: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: guruprasad
          property: connectionString

databases:
  - name: guruprasad
    plan: free
